# Generated by Django 2.1.7 on 2019-02-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('organizationname', models.CharField(blank=True, db_column='OrganizationName', max_length=255, null=True)),
                ('organizationlocation', models.CharField(blank=True, db_column='OrganizationLocation', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('permissionname', models.CharField(blank=True, db_column='PermissionName', max_length=255, null=True)),
                ('permissionactive', models.TextField(db_column='PermissionActive')),
                ('create', models.TextField(db_column='Create')),
                ('read', models.TextField(db_column='Read')),
                ('update', models.TextField(db_column='Update')),
                ('delete', models.TextField(db_column='Delete')),
                ('read_others', models.TextField(db_column='Read_others')),
                ('update_others', models.TextField(db_column='Update_others')),
            ],
            options={
                'db_table': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('profilename', models.CharField(blank=True, db_column='ProfileName', max_length=255, null=True)),
                ('active', models.TextField(db_column='Active')),
                ('userid', models.IntegerField(db_column='UserID')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=255, null=True)),
                ('useremail', models.CharField(blank=True, db_column='UserEmail', max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('userrole', models.CharField(blank=True, db_column='UserRole', max_length=255, null=True)),
                ('active', models.TextField(db_column='Active')),
                ('organizationid', models.ForeignKey(db_column='OrganizationID', on_delete=django.db.models.deletion.DO_NOTHING, to='Users.Organization')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='ProfilePermission',
            fields=[
                ('profileid', models.ForeignKey(db_column='ProfileID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Users.Profile')),
                ('permissionid', models.ForeignKey(db_column='PermissionID', on_delete=django.db.models.deletion.DO_NOTHING, to='Users.Permission')),
            ],
            options={
                'db_table': 'Profile_Permission',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='profileid',
            field=models.ForeignKey(db_column='ProfileID', on_delete=django.db.models.deletion.DO_NOTHING, to='Users.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='profilepermission',
            unique_together={('profileid', 'permissionid')},
        ),
    ]
