# Generated by Django 2.1.7 on 2019-02-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190228_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organizationid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profileid',
        ),
    ]
